Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -33,29 +33,30 @@ jobs:
             exit 1
           fi
           
-          # Print aapt output for debugging
-          aapt dump badging app-release.apk | grep versionName
-          
-          # Extract correct version name
           APK_VERSION=$(aapt dump badging app-release.apk | awk -F"versionName='" '{print $2}' | awk -F"'" '{print $1}')
           
           if [[ -z "$APK_VERSION" ]]; then
             echo "Error: Failed to extract APK version!"
             exit 1
           fi
-          
+
+          NEW_APK_NAME="hrms_v${APK_VERSION}.apk"
+          mv app-release.apk "$NEW_APK_NAME"
+
           echo "APK_VERSION=$APK_VERSION" >> $GITHUB_ENV
+          echo "APK_FILE=$NEW_APK_NAME" >> $GITHUB_ENV
           echo "Extracted APK Version: $APK_VERSION"
+          echo "Renamed APK: $NEW_APK_NAME"
 
       - name: Push to release
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "app-release.apk"
+          artifacts: ${{ env.APK_FILE }}
           tag: ${{ env.APK_VERSION }}
           token: ${{ secrets.PUBLIC_REPO }}
 
       - name: Set release URL
-        run: echo "RELEASE_URL=https://github.com/${{ github.repository }}/releases/download/${{ env.APK_VERSION }}/app-release.apk" >> $GITHUB_ENV
+        run: echo "RELEASE_URL=https://github.com/${{ github.repository }}/releases/download/${{ env.APK_VERSION }}/${{ env.APK_FILE }}" >> $GITHUB_ENV
 
       - name: Update JSON File for app update
         run: |
@@ -73,29 +74,87 @@ jobs:
          git commit -m "Updated custom.json file"
          git push
 
-
-      #### for All tech team
-      # - name: Get Release apk and Send Email
+      # - name: Get Release apk and Send Email 
       #   run: | 
-      #     RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${{ env.APK_VERSION }}/app-release.apk"
       #     echo "Download URL: $RELEASE_URL"
       #     curl --location 'https://api.mailgun.net/v3/salaryontime.com/messages' \
       #       --header 'Authorization: Basic YXBpOjM1NGRkNjZhNjllN2UzZDVjNDc0NzE5NWRiNTVhM2RkLWFjM2Q1Zjc0LWQ3ODEwZWU3' \
       #       --form 'from="info@salaryontime.com"' \
-      #       --form 'to="arvind@salaryontime.com, bhavish@salaryontime.com, Megha@salaryontime.com, alam@salaryontime.com, ashutosh@salaryontime.com, ishu@salaryontime.com, ajit@salaryontime.com, rohit@salaryontime.com, kasim@salaryontime.com"' \
+      #       --form 'to="arvind@salaryontime.com, bhavish@salaryontime.com, megha@salaryontime.com"' \
       #       --form "text=Click on the link to download HRMS app: $RELEASE_URL" \
-      #       --form 'subject="HRMS app version: $RELEASE_URL"'
+      #       --form 'subject=HRMS app version: ${{ env.APK_VERSION }}'
 
-      ### for 3 people
-      - name: Get Release apk and Send Email 
-        run: | 
-          echo "Download URL: $RELEASE_URL"
-          curl --location 'https://api.mailgun.net/v3/salaryontime.com/messages' \
-            --header 'Authorization: Basic YXBpOjM1NGRkNjZhNjllN2UzZDVjNDc0NzE5NWRiNTVhM2RkLWFjM2Q1Zjc0LWQ3ODEwZWU3' \
-            --form 'from="info@salaryontime.com"' \
-            --form 'to="arvind@salaryontime.com, bhavish@salaryontime.com megha@salaryontime.com"' \
-            --form "text=Click on the link to download HRMS app:  $RELEASE_URL" \
-            --form 'subject="HRMS app version: $RELEASE_URL"'
+
+      # - name: Extract APK Version
+      #   run: |
+      #     if [[ ! -f "app-release.apk" ]]; then
+      #       echo "Error: APK file not found!"
+      #       exit 1
+      #     fi
+          
+      #     # Print aapt output for debugging
+      #     aapt dump badging app-release.apk | grep versionName
+          
+      #     # Extract correct version name
+      #     APK_VERSION=$(aapt dump badging app-release.apk | awk -F"versionName='" '{print $2}' | awk -F"'" '{print $1}')
+          
+      #     if [[ -z "$APK_VERSION" ]]; then
+      #       echo "Error: Failed to extract APK version!"
+      #       exit 1
+      #     fi
+          
+      #     echo "APK_VERSION=$APK_VERSION" >> $GITHUB_ENV
+      #     echo "Extracted APK Version: $APK_VERSION"
+
+      # - name: Push to release
+      #   uses: ncipollo/release-action@v1
+      #   with:
+      #     artifacts: "app-release.apk"
+      #     tag: ${{ env.APK_VERSION }}
+      #     token: ${{ secrets.PUBLIC_REPO }}
+
+      # - name: Set release URL
+      #   run: echo "RELEASE_URL=https://github.com/${{ github.repository }}/releases/download/${{ env.APK_VERSION }}/app-release.apk" >> $GITHUB_ENV
+
+      # - name: Update JSON File for app update
+      #   run: |
+      #    echo "Download URL: $RELEASE_URL"
+      #    echo '{
+      #     "version": "'${{ env.APK_VERSION }}'",
+      #     "url": "'$RELEASE_URL'"
+      #    }' > check_app_version.json 
+
+      # - name: Commit and Push JSON File
+      #   run: |
+      #    git config --global user.email "bhavish@salaryontime.com"
+      #    git config --global user.name "BhavishBhavish"
+      #    git add check_app_version.json
+      #    git commit -m "Updated custom.json file"
+      #    git push
+
+
+      # #### for All tech team
+      # # - name: Get Release apk and Send Email
+      # #   run: | 
+      # #     RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${{ env.APK_VERSION }}/app-release.apk"
+      # #     echo "Download URL: $RELEASE_URL"
+      # #     curl --location 'https://api.mailgun.net/v3/salaryontime.com/messages' \
+      # #       --header 'Authorization: Basic YXBpOjM1NGRkNjZhNjllN2UzZDVjNDc0NzE5NWRiNTVhM2RkLWFjM2Q1Zjc0LWQ3ODEwZWU3' \
+      # #       --form 'from="info@salaryontime.com"' \
+      # #       --form 'to="arvind@salaryontime.com, bhavish@salaryontime.com, Megha@salaryontime.com, alam@salaryontime.com, ashutosh@salaryontime.com, ishu@salaryontime.com, ajit@salaryontime.com, rohit@salaryontime.com, kasim@salaryontime.com"' \
+      # #       --form "text=Click on the link to download HRMS app: $RELEASE_URL" \
+      # #       --form 'subject="HRMS app version: $RELEASE_URL"'
+
+      # ### for 3 people
+      # - name: Get Release apk and Send Email 
+      #   run: | 
+      #     echo "Download URL: $RELEASE_URL"
+      #     curl --location 'https://api.mailgun.net/v3/salaryontime.com/messages' \
+      #       --header 'Authorization: Basic YXBpOjM1NGRkNjZhNjllN2UzZDVjNDc0NzE5NWRiNTVhM2RkLWFjM2Q1Zjc0LWQ3ODEwZWU3' \
+      #       --form 'from="info@salaryontime.com"' \
+      #       --form 'to="arvind@salaryontime.com, bhavish@salaryontime.com megha@salaryontime.com"' \
+      #       --form "text=Click on the link to download HRMS app:  $RELEASE_URL" \
+      #       --form 'subject="HRMS app version: $RELEASE_URL"'
 
 
 
